apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
data:
  identity-allocation-mode: crd
  debug: "false"
  enable-ipv4: "true"
  enable-ipv6: "false"
  monitor-aggregation: medium
  monitor-aggregation-interval: 5s
  monitor-aggregation-flags: all
  bpf-ct-global-tcp-max: "524288"
  bpf-ct-global-any-max: "262144"
  preallocate-bpf-maps: "true"
  sidecar-istio-proxy-image: "cilium/istio_proxy"
  tunnel: disabled
  tofqdns-enable-poller: "false"
  wait-bpf-mount: "true"
  masquerade: "true"
  cni-chaining-mode: "generic-veth"
  custom-cni-conf: "true"
  read-cni-conf: /tmp/cni-configuration/cni-config
  write-cni-conf-when-ready: /host/etc/cni/net.d/05-cilium.conflist
  enable-bpf-masquerade: "true"
  enable-xt-socket-fallback: "true"
  kube-proxy-replacement: "strict"
