apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
data:
  identity-allocation-mode: crd
  debug: "false"
  enable-ipv4: "true"
  enable-ipv6: "false"
  monitor-aggregation: medium
  monitor-aggregation-interval: 5s
  monitor-aggregation-flags: all
  bpf-ct-global-tcp-max: "524288"
  bpf-ct-global-any-max: "262144"
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: "cilium/istio_proxy"
  tunnel: vxlan
  tofqdns-enable-poller: "false"
  wait-bpf-mount: "true"
  masquerade: "true"
  enable-bpf-masquerade: "false"
  enable-xt-socket-fallback: "true"
  install-iptables-rules: "true"
  auto-direct-node-routes: "false"
  kube-proxy-replacement:  "strict"
  node-port-bind-protection: "true"
  enable-auto-protect-node-port-range: "true"
  enable-session-affinity: "true"
  # Chaining mode is set to portmap, enable health checking
  enable-endpoint-health-checking: "true"
  enable-well-known-identities: "false"
  enable-remote-node-identity: "true"

  synchronize-k8s-nodes: "true"
  policy-audit-mode: "false"
  operator-api-serve-addr: '127.0.0.1:9234'

  # Enable Hubble gRPC service.
  enable-hubble: "false"

  # A space separated list of iptables chains to disable when installing feeder rules.
  disable-iptables-feeder-rules: ""
