kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: kube-system
  labels:
    tier: node
    app: multus
data:
  # NOTE: If you'd prefer to manually apply a configuration file, you may create one here.
  # In the case you'd like to customize the Multus installation, you should change the arguments to the Multus pod
  # change the "args" line below from
  # - "--multus-conf-file=auto"
  # to:
  # "--multus-conf-file=/tmp/multus-conf/70-multus.conf"
  # Additionally -- you should ensure that the name "70-multus.conf" is the alphabetically first name in the
  # /etc/cni/net.d/ directory on each node, otherwise, it will not be used by the Kubelet.
  00-multus.conf: |
    {
        "cniVersion": "0.3.1",
        "name": "multus-cni-network",
        "type": "multus",
        "namespaceIsolation": true,
        "logLevel": "verbose",
        "binDir": "/opt/multus/bin",
        "kubeconfig": "/etc/kubernetes/cni/net.d/multus.d/multus.kubeconfig",
        "delegates": [
            {
                "cniVersion": "0.3.1",
                "name": "cilium",
                "type": "cilium-cni",
                "enable-debug": false
            },
            {
              "type": "portmap",
              "capabilities": {
                "portMappings": true
              }
            }
        ]
    }
